server:
 port: 9090

spring:
 application.name: productapp
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/maybankproject
  username: root
  password: root

 jpa:
  generate-ddl: true
  properties.hibernate.format_sql: true
  
company:
 name: Maybank
 city: Banglore
 ceoName: Varun
